apiVersion: v1
kind: Service
metadata:
  name: nginx-ser
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
      nodePort: {{ .Values.nginx.service.nodePort }}
