apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-pod
  ports:
    - protocol: TCP
      port: {{ .Values.php.service.port }}
      targetPort: 9000
  type: {{ .Values.php.service.type }}
