apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: postgres-pod
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
