version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkinsfast:/var/jenkins_home  # Mounting workspace
    environment:
      - JAVA_OPTS=-Xmx2048m  # Allocating 2GB memory for Jenkins
    deploy:
      resources:
        limits:
          cpus: "2"       # Limit Jenkins to 2 CPU cores
          memory: "4GB"   # Limit Jenkins to 4GB RAM
        reservations:
          cpus: "1"       # Reserve 1 CPU core
          memory: "2GB"   # Reserve 2GB RAM
