apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python.fullname" . }}
  labels:
   {{- include "python.labels" . | nindent 4 }}
    env: {{ .Values.pythonredis.pod.labelEnv }}
spec:
  replicas: {{ .Values.pythonredis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pythonredis.labelsapp }}
      env: {{ .Values.pythonredis.pod.labelEnv }}
     

  template:
    metadata:
      labels:
        app: {{ .Values.pythonredis.pod.labelApp }}
        env: {{ .Values.pythonredis.pod.labelEnv }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pythonredis.image.repository }}:{{ .Values.pythonredis.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.pythonredis.service.port }}
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
   {{- include "redis.labels" . | nindent 4 }}
    env: {{ .Values.redis.pod.labelEnv }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.labelsapp }}
      env: {{ .Values.redis.pod.labelEnv }}
     

  template:
    metadata:
      labels:
        app: {{ .Values.redis.pod.labelApp }}
        env: {{ .Values.redis.pod.labelEnv }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP